             <!--page title-->
             <div class="pagetitle">
                <h1>Buttons.</h1> 
                <div class="btn-group">
                  <button class="btn">Day</button>
                  <button class="btn">Week</button>
                  <button class="btn">Month</button>
                </div>
                <div class="clearfix"></div>
             </div>
             <!--page title end-->
             
             <!--Buttons Start-->
                <div class="grid">
                  <div class="grid-title">
                   <div class="pull-left">
                      <div class="icon-title"><i class="icon-reorder"></i></div>
                      <span>Buttons</span> 
                      <div class="clearfix"></div>
                   </div>
                   <div class="pull-right"> 
                      <div class="icon-title"><a href="#"><i class="icon-refresh"></i></a></div>
                      <div class="icon-title"><a href="#"><i class="icon-cog"></i></a></div>
                   </div>
                  <div class="clearfix"></div>   
                  </div>
                  <div class="grid-content buttons-mob">
                  
        
                             <input type="submit" class="btn btn-large" value="Large">
                             <input type="submit" class="btn btn-primary btn-large" value="Large">
                             <input type="submit" class="btn btn-info btn-large" value="Large">
                             <input type="submit" class="btn btn-success btn-large" value="Large">
                             <input type="submit" class="btn btn-warning btn-large" value="Large">
                             <input type="submit" class="btn btn-danger btn-large" value="Large">
                             <input type="submit" class="btn btn-inverse btn-large" value="Large">  
                             <div class="seperator_dashed"></div>
                             <input type="submit" class="btn" value="Default">
                             <input type="submit" class="btn btn-primary" value="Default">
                             <input type="submit" class="btn btn-info" value="Default">
                             <input type="submit" class="btn btn-success" value="Default">
                             <input type="submit" class="btn btn-warning" value="Default">
                             <input type="submit" class="btn btn-danger" value="Default">
                             <input type="submit" class="btn btn-inverse" value="Default">    
                             <div class="seperator_dashed"></div>
                             <input type="submit" class="btn btn-small" value="Small">
                             <input type="submit" class="btn btn-primary btn-small" value="Small">
                             <input type="submit" class="btn btn-info btn-small" value="Small">
                             <input type="submit" class="btn btn-success btn-small" value="Small">
                             <input type="submit" class="btn btn-warning btn-small" value="Small">
                             <input type="submit" class="btn btn-danger btn-small" value="Small">
                             <input type="submit" class="btn btn-inverse btn-small" value="Small"> 
                             <div class="seperator_dashed"></div>
                             <button class="btn  btn-mini">Mini</button>
                             <button class="btn  btn-primary btn-mini">Mini</button>
                             <button class="btn  btn-info btn-mini">Mini</button>
                             <button class="btn  btn-success btn-mini">Mini</button>
                             <button class="btn  btn-warning btn-mini">Mini</button>
                             <button class="btn  btn-danger btn-mini">Mini</button>
                             <button class="btn  btn-inverse btn-mini">Mini</button>       
            
                    <div class="clear"></div>
                  
                  </div>    
                </div>
                <!--Buttons END-->
                
                <!--Buttons dropdowns Start-->
                <div class="grid">
                  <div class="grid-title">
                   <div class="pull-left">
                      <div class="icon-title"><i class="icon-reorder"></i></div>
                      <span>Buttons dropdowns</span> 
                      <div class="clearfix"></div>
                   </div>
                   <div class="pull-right"> 
                      <div class="icon-title"><a href="#"><i class="icon-refresh"></i></a></div>
                      <div class="icon-title"><a href="#"><i class="icon-cog"></i></a></div>
                   </div>
                  <div class="clearfix"></div>   
                  </div>
                  <div class="grid-content buttons-mob">
                                     <div class="buttons_set">
                     <div class="btn-group">
                          <button class="btn btn-large dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-primary dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-info dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-success dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-warning dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-danger dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-inverse dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                </div>
                <div class="clear"></div>
                <div class="seperator_dashed"></div>
                
                <div class="buttons_set">
                     <div class="btn-group">
                          <button class="btn dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-warning dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                    </div>
                    
                    <div class="clear"></div>
                    <div class="seperator_dashed"></div>
                    
                    <div class="buttons_set">
                    <div class="btn-group dropup">
                          <button class="btn dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-info dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-success dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-warning dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-danger dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                    </div>
                    
                    <div class="clear"></div>
                    <div class="seperator_dashed"></div>
                    
                    <div class="buttons_set">
                     <div class="btn-group">
                          <button class="btn btn-mini dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-primary dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-info dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-success dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-warning dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-danger dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-inverse dropdown-toggle" data-toggle="dropdown">Action <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                    </div>
                    
                    <div class="clear"></div>     
                  
                  </div>    
                </div>
                <!--Buttons dropdowns END-->
                
                <!--Split button dropdowns Start-->
                <div class="grid">
                  <div class="grid-title">
                   <div class="pull-left">
                      <div class="icon-title"><i class="icon-reorder"></i></div>
                      <span>Split button dropdowns</span> 
                      <div class="clearfix"></div>
                   </div>
                   <div class="pull-right"> 
                      <div class="icon-title"><a href="#"><i class="icon-refresh"></i></a></div>
                      <div class="icon-title"><a href="#"><i class="icon-cog"></i></a></div>
                   </div>
                  <div class="clearfix"></div>   
                  </div>
                  <div class="grid-content buttons-mob">
                   <div class="buttons_set">
                     <div class="btn-group">
                          <button class="btn btn-large">Action</button>
                          <button class="btn btn-large dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-primary">Action</button>
                          <button class="btn btn-large btn-primary dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-info">Action</button>
                          <button class="btn btn-large btn-info dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-success">Action</button>
                          <button class="btn btn-large btn-success dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-warning">Action</button>
                          <button class="btn btn-large btn-warning dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-danger">Action</button>
                          <button class="btn btn-large btn-danger dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-large btn-inverse">Action</button>
                          <button class="btn btn-large btn-inverse dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                </div>
                <div class="clear"></div>
                <div class="seperator_dashed"></div>
                
                <div class="buttons_set">
                     <div class="btn-group">
                          <button class="btn">Action</button>
                          <button class="btn dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-primary">Action</button>
                          <button class="btn btn-primary dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-info">Action</button>
                          <button class="btn btn-info dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-success">Action</button>
                          <button class="btn btn-success dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-warning">Action</button>
                          <button class="btn btn-warning dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-danger">Action</button>
                          <button class="btn btn-danger dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-inverse">Action</button>
                          <button class="btn btn-inverse dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                    </div>
                    
                    <div class="clear"></div>
                    <div class="seperator_dashed"></div>
                    
                    <div class="buttons_set">
                     <div class="btn-group dropup">
                          <button class="btn">Action</button>
                          <button class="btn dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-primary">Action</button>
                          <button class="btn btn-primary dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-info">Action</button>
                          <button class="btn btn-info dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-success">Action</button>
                          <button class="btn btn-success dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-warning">Action</button>
                          <button class="btn btn-warning dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-danger">Action</button>
                          <button class="btn btn-danger dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group dropup">
                          <button class="btn btn-inverse">Action</button>
                          <button class="btn btn-inverse dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                    </div>
                    
                    <div class="clear"></div>
                    <div class="seperator_dashed"></div>
                    
                    <div class="buttons_set">
                     <div class="btn-group">
                          <button class="btn btn-mini">Action</button>
                          <button class="btn btn-mini dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-primary">Action</button>
                          <button class="btn btn-mini btn-primary dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-info">Action</button>
                          <button class="btn btn-mini btn-info dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-success">Action</button>
                          <button class="btn btn-mini btn-success dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-warning">Action</button>
                          <button class="btn btn-mini btn-warning dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group ">
                          <button class="btn btn-mini btn-danger">Action</button>
                          <button class="btn btn-mini btn-danger dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                     <div class="btn-group">
                          <button class="btn btn-mini btn-inverse">Action</button>
                          <button class="btn btn-mini btn-inverse dropdown-toggle b2" data-toggle="dropdown"><span class="caret"></span></button>   
                            <ul class="dropdown-menu">
                                 <li><a href="#"><i class="icon-trash"></i> Remove all</a></li>
                                 <li><a href="#"><i class="icon-music"></i> Play all</a></li>
                                 <li><a href="#"><i class="icon-plus-sign"></i> Add to Favorites</a></li>
                            </ul>
                     </div><!-- /btn-group -->
                    </div>
                    
                    <div class="clear"></div>
                  
                  </div>    
                </div>
                <!--Split button dropdowns END-->
                
                <!--Buttons METRO Start-->
                <div class="grid">
                  <div class="grid-title">
                   <div class="pull-left">
                      <div class="icon-title"><i class="icon-reorder"></i></div>
                      <span>Metro Style</span> 
                      <div class="clearfix"></div>
                   </div>
                   <div class="pull-right"> 
                      <div class="icon-title"><a href="#"><i class="icon-refresh"></i></a></div>
                      <div class="icon-title"><a href="#"><i class="icon-cog"></i></a></div>
                   </div>
                  <div class="clearfix"></div>   
                  </div>
                  <div class="grid-content buttons-mob">
                  
        
                             <input type="submit" class="btn btn-large metro" value="Large">
                             <input type="submit" class="btn btn-primary btn-large metro" value="Large">
                             <input type="submit" class="btn btn-success btn-large metro" value="Large">
                             <input type="submit" class="btn btn-warning btn-large metro" value="Large">
                             <input type="submit" class="btn btn-danger btn-large metro" value="Large">
                             <input type="submit" class="btn btn-inverse btn-large metro" value="Large">  
                             <div class="seperator_dashed"></div>
                             <input type="submit" class="btn metro" value="Default">
                             <input type="submit" class="btn btn-primary metro" value="Default">
                             <input type="submit" class="btn btn-success metro" value="Default">
                             <input type="submit" class="btn btn-warning metro" value="Default">
                             <input type="submit" class="btn btn-danger metro" value="Default">
                             <input type="submit" class="btn btn-inverse metro" value="Default">    
                             <div class="seperator_dashed"></div>
                             <input type="submit" class="btn btn-small metro" value="Small">
                             <input type="submit" class="btn btn-primary btn-small metro" value="Small">
                             <input type="submit" class="btn btn-success btn-small metro" value="Small">
                             <input type="submit" class="btn btn-warning btn-small metro" value="Small">
                             <input type="submit" class="btn btn-danger btn-small metro" value="Small">
                             <input type="submit" class="btn btn-inverse btn-small metro" value="Small"> 
                             <div class="seperator_dashed"></div>
                             <button class="btn  btn-mini metro">Mini</button>
                             <button class="btn  btn-primary btn-mini metro">Mini</button>
                             <button class="btn  btn-success btn-mini metro">Mini</button>
                             <button class="btn  btn-warning btn-mini metro">Mini</button>
                             <button class="btn  btn-danger btn-mini metro">Mini</button>
                             <button class="btn  btn-inverse btn-mini metro">Mini</button>       
            
                    <div class="clear"></div>
                  
                  </div>    
                </div>
                <!--Buttons METRO END-->
